
#Local Server Config
#uploadFilePath = D:/FileStore
#endorsedSop = C:/SOP_BACKEND/Endorsed SOP/File
#sopCover = C:/SOP_Project/src/main/resources/templates/sopCover.jpg
#publicKeyFileStore = E:/SSO_KEYSTORE

#Test server Config

#uploadFilePath = /var/lib/tomcat9/webapps/FileStore/sopAttachment
#endorsedSop = /var/lib/tomcat9/webapps/FileStore/endorsedSop
#publicKeyFileStore = /var/lib/tomcat9/webapps/KEYSTORE
#sopCover = /var/lib/tomcat9/webapps/templates/sop_cover.png

#Live Server Config
uploadFilePath = /var/lib/webapp/FileStore/sopAttachment
endorsedSop = /var/lib/webapp/FileStore/endorsedSop
publicKeyFileStore = /var/lib/webapp/KEYSTORE
sopCover = /var/lib/webapp/templates/sopCover.jpg











