smscUsername=sop
smscPassword=sop23
systemType=NULL
addressRange=NULL
smscHost=10.76.177.100
smscPort=8443
#BIND_TIMEOUT=2000
serviceType=CMT
senderPhoneNumber=SOP



#For Local
#sms.url.firstPart=http://118.103.137.224:80/cgi-bin/BMP_SendTextMsg?

#For Live
sms.url.firstPart=http://10.76.177.100:80/cgi-bin/BMP_SendTextMsg?
