#region email properties
#mail.fromAddress = default@gmail.com

mail.fromAddress = ticl-alerts@tashicell.com
mail.username = ticl-alerts@tashicell.com
mail.password = @NPAv6TZGP
mail.host = smtp1.tashicell.com
#mail.host = smtp.gmail.com
mail.port = 587
#mail.port = 465
mail.auth = true
mail.startLlsEnable = true
mail.encryption = tls
mail.mailer = smtp

mail.smtpHost = mail.smtp.host
mail.smtpPort = mail.smtp.port
mail.smtpAuth = mail.smtp.auth
mail.smtpStartLlsEnable = mail.smtp.starttls.enable
mail.isRequiredToSend = 1
#endregion